# -*- coding: utf-8 -*-
#
# Copyright (C) 2020 CERN.
#
# Marshmallow-Utils is free software; you can redistribute it and/or modify
# it under the terms of the MIT License; see LICENSE file for more details.

notifications:
  email: false

sudo: false

language: python

matrix:
  fast_finish: true

cache:
  - pip

env:
  - REQUIREMENTS=lowest
  - REQUIREMENTS=release DEPLOY=true

python:
  - "3.6"
  - "3.7"
  - "3.8"

before_install:
  - "travis_retry pip install --upgrade pip setuptools py"
  - "travis_retry pip install twine wheel coveralls requirements-builder"
  - "requirements-builder -e all --level=min setup.py > .travis-lowest-requirements.txt"
  - "requirements-builder -e all --level=pypi setup.py > .travis-release-requirements.txt"

install:
  - "travis_retry pip install -r .travis-${REQUIREMENTS}-requirements.txt"
  - "travis_retry pip install -e .[all]"

script:
  - "./run-tests.sh"

after_success:
  - coveralls

deploy:
  provider: pypi
  user: inveniosoftware
  password:
    secure: TODO:PYPISECUREHASH
  distributions: "sdist bdist_wheel"
  on:
    tags: true
    python: "3.8"
    repo: inveniosoftware/marshmallow-utils
    condition: $DEPLOY = true
